### ISSUE TITLE
Report status on Alarm screen, to assist diagnosis

### ISSUE THREAD

**Issue by Neex101** [YetiTool/easycut-smartbench#413]
If a limit switch fails mid operation, this is difficult to diagnose.
Reporting the latest status line back from grbl (e.g. <Idle|MPos:0.000,0.000,0.000|Bf:35,255|FS:0,0|Pn:PxXyYZ> )
into the screen diagnosis would really help diagnostics over the phone

**Comment by LettyYeti** [comment]
Can't do this direct to the alarm screen without fiddling with how the alarm screen resume/reset works, or without fiddling around to keep/get the last position line before the alarm message comes from grbl.

Have put in an alternative where alarm position messages now print to gcode monitor (not the live status, the static bit) so you can still see what's happening at resume time. 

@Neex101  will consider this fixed when I push to master unless you want to request otherwise
